import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { User } from "lucide-react";
import { AdminSidebar } from "@/components/AdminSidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full">
        <SidebarProvider defaultOpen>
          <div className="flex min-h-screen bg-[#F4F4F5]">
            <AdminSidebar />

            <SidebarInset className="bg-transparent">
              <div className="flex min-h-screen flex-col px-8 py-8">
                <div className="flex justify-end">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-black text-white">
                    <User className="size-4" strokeWidth={2.4} />
                  </div>
                </div>

                {children}
              </div>
            </SidebarInset>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
